environment_parameters:

  difficulty_ratio:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.10
        value: 0.40

      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.15
        value: 0.45

      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.20
        value: 0.50

      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.25
        value: 0.56

      - name: Lesson4
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.30
        value: 0.62

      - name: Lesson5
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.40
        value: 0.68

      - name: Lesson6
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.50
        value: 0.75

      - name: Lesson7
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.60
        value: 0.85

      - name: Lesson8
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.66
        value: 0.92

      - name: Lesson9
        value: 1.0
        
  smoothness_progression:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.10
        value: 0.0

      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.15
        value: 0.1

      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.20
        value: 0.2

      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.25
        value: 0.3

      - name: Lesson4
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.30
        value: 0.4

      - name: Lesson5
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.40
        value: 0.6

      - name: Lesson6
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.50
        value: 0.7

      - name: Lesson7
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.60
        value: 0.85

      - name: Lesson8
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.66
        value: 0.95

      - name: Lesson9
        value: 1.0
        
  dtc_progression:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.10
        value: 0.0

      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.15
        value: 0.1

      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.20
        value: 0.2

      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.25
        value: 0.3

      - name: Lesson4
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 75
          threshold: 0.30
        value: 0.4

      - name: Lesson5
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.40
        value: 0.6

      - name: Lesson6
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.50
        value: 0.7

      - name: Lesson7
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.60
        value: 0.85

      - name: Lesson8
        completion_criteria:
          measure: progress
          behavior: TestModel
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.66
        value: 0.95

      - name: Lesson9
        value: 1.0