behaviors:
  TestModel:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 81920
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      epsilon_schedule: linear   
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      use_recurrent: true
      sequence_length: 16 
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 320000000  # ~ 5.000.000 times Envs (16) times Agents (4)
    time_horizon: 64
    summary_freq: 320000  # ~ 5.000 times Envs (16) times Agents (4)
    threaded: true
